### ISSUE TITLE
Refactor Listener cleaner to a listener manager

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#15]
in the moment you have to register listeners by yours self, by doing

aProperty().addListener(listener);

//and then you had to use the cleaner like this:

listenerCleaner.put(aProperty,listener);

This could be improved by giving a method which registers the listener for you

**Comment by sialcasa** [comment]
todo: 
Rename ListenerCleaner to Listener manager
Rename put functions to talking name 

//Internal: property.addListener(listener); + listenerCleaner.put(ALL_PROPERTY_TYPES property,LISTENER INSTANCE listener);
listenerCleaner.addListener(ALL_PROPERTY_TYPES property,LISTENER INSTANCE listener);

//Internal: remove all registered Listeners from property
listenerCleaner.removeAllListeners(ALL_PROPERTYTYPES property);

**Comment by manuel-mauky** [comment]
I'm not sure what's the best semantic for the `remove` method. In the new `put` method we now add the listener to the property (`property.addListener(listener)`). Do you think it would then be the best to call `removeListener` in the new `remove` method as well?
In the current ListenerCleaner the `remove` method only removes the listener and property from the internal map so that it will not be processed by `clean`. But the listener is still attached to the property. Do we want to keep this behaviour?
