### ISSUE TITLE
Access ResourceBundles in ViewModel

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#176]

**Comment by sialcasa** [comment]
- @InjectResourceBundle for View und ViewModel
- has to be compatible with standard resourcebundle

**Comment by manuel-mauky** [comment]
In Views and ViewModels you can now inject the ResourceBundle with `@InjectResourceBundle`.
With this approach the developer can be more explicit about the injection and will get some checks done by the framework: 
An exception will be thrown when:
- the field that is annotated is not of type `ResourceBundle`
- there is a field annotated with `@InjectResourceBundle` but no ResourceBundle was provided durring the loading of the View.

The second check can be disabled via the attribute `optional` in the annotation. This way the ResourceBundle will be injected if it was provided durring the loading. Otherwise nothing will happen either.

```
public class MyViewModel implements ViewModel {
    @InjectResourceBundle(optional = true)
    private ResourceBundle resourceBundle;
}
```

**Comment by manuel-mauky** [comment]
There is still a problem with this solution: In the ViewModel there is no `initialize` method where the developer can create bindings based on injected values. Even when using a dependency injection framework with a `@PostConstruct` method this isn't working because the post construct method will be invoked before we can inject the ResourceBundle. 

To circumvent this we could provide the possibility to inject the ResourceBundle into an `ObjectProperty<ResourceBundle>` instance. This way one could do something like this:

```
@InjectResourceBundle
private ObjectProperty<ResourceBundle> resourceBundle = new SimpleObjectProperty<>();

private StringProperty myValue = new SimpleStringProperty();

public MyViewModel(){
    myValue.bind( Bindings.createStringBinding(
        ()-> resourceBundle.getValue().getString("myKey"), 
        resourceBundle));
}
```

**Comment by sialcasa** [comment]
Sounds Good, what about using the concept for scopes too?

**Comment by manuel-mauky** [comment]
We will not implement the injection into Properties like proposed in the previous comment. Instead we will implement a lifecycle method for the initialization of the ViewModel (#185). 

The reason for this is to prevent a wild mix of initialization styles. The "initialization" naming convention is used by standard JavaFX and is supported for our Views too.
