### ISSUE TITLE
Guice vs CDI

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#33]
We need to find a better way of dependency injection. At the moment we have maven dependencies to both CDI/Weld and Guice frameworks. 
We need to check whether it is possible to split and separate the depenencies so that the user can choose the DI framework and doesn't need the dependencies for the other framework. Probably this can be done with different Maven modules.

If this doesn't work we probably need to use and support only one of the DI frameworks. In this case we need to find out which framework is doing the best job for the use cases mvvmfx is designed for.

**Comment by guigarage** [comment]
Hi,
I currently have the same issues with DataFX. Maybe we can find a way that fits for both frameworks.
In JEE you have the JSR-299 spec that defines a lot of useful interfaces. The problem is that a part of these classes only fit for JEE. You will never need a RequestScope in JavaFX / JavaSE for example. Currently I plan to create a project that will include only a part of JSR-299 (Annotations like @Inject etc.). Maybe we can create this and use it in mvvmFX and DataFX :)

Cheers,
Hendrik

**Comment by manuel-mauky** [comment]
Hi Hendrik,
this sounds great. I was already asking myself if we are the only ones that are facing this problem.

It would be great if we find a reusable way of abstracting the specific DI frameworks and I realy like the idea to create an independent project for this so that we both can use it for our frameworks (and others too).

Best regards,
Manuel

**Comment by guigarage** [comment]
I created a repo: https://bitbucket.org/guigarage/contexts-and-dependency-injection-for-javafx

**Comment by manuel-mauky** [comment]
I have extracted the dependency to specific DI frameworks from the core framework and created a way to tell mvvmfx how your specific DI is working. This way the user can use the DI framework he likes - or even work without DI.

For simplification I created two extension modules for CDI and guice that the user can use for an easier setup when he uses one of these DI frameworks. The main difference is that this is now fully optional and the user isn't forced to use one of these frameworks. I think for our usecase this is the best solution.
