### ISSUE TITLE
@InjectViewModel doesn't inject viewModel for Guice AOP-ed views

### ISSUE THREAD

**Issue by archislav** [sialcasa/mvvmFX#335]
For example, we have 

``` java
public class UserView implements FxmlView<UserViewModel>, Initializable {

@InjectViewModel
private UserViewModel viewModel;

 @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
                                viewModel.getUsers() // here viewModel is null
);
```

and guice module with interceptor

``` java
public class InterceptorModule implements Module {
    @Override
    public void configure(Binder binder) {
            binder.bindInterceptor(
                    Matchers.subclassesOf(UserView.class), Matchers.any(), new MyInterceptor());    
}
```

ViewLoaderReflectionUtils::getViewModelField returns Optional.empty in this case.

**Comment by manuel-mauky** [comment]
Hi archislav,
thanks for reporting. I will take a closer look into this issue next week. 
We haven't tried out guice interceptors yet because for our internal projects we mostly use CDI. 
Our guice module is based on the [fx-guice](https://github.com/cathive/fx-guice) project. Do you know if interceptors are working there?

**Comment by archislav** [comment]
Hi, Lestard. I've checked fx-guice - it works fine with interceptors (It also provides FxApplicationThread annotation for executing method in JavaFX thread). 

de.saxsys.mvvmfx.internal.viewloader.ViewLoaderReflectionUtils::getViewModelField tries to find @InjectViewModel only in current viewType, but in case of interceptors Guice creates subclass of viewType - that why it can't find such field.

**Comment by manuel-mauky** [comment]
Many thanks for your hints. It helped a lot. 

With PR #336 I've now changed the getViewModelFields method so that it searches in the whole class hierarchy to find the correct field. A test case with a guice interceptor now runs green. 

A snapshot version with this bugfix will be automatically pushed to maven central so you can test it. Use version 1.4.1-SNAPSHOT. 
We are planing to release the final 1.4.1. version next week.
