### ISSUE TITLE
[notifications]  The notification mechanism between VM and V may leak.

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#378]
Currently the ViewModel gets referenced in the global Notification Center when the subscribe method in interface ViewModel is called. This may create memory leaks, because the ViewModel is still referenced as an Observer in the Notification Center, when it is expected to be garbage collected.

This is due to:

Everything you register as the recipient of an Event, e.g. in GUI frameworks, cannot be garbage collected as long as it is registered and the event source is alive.

This may introduce memory leaks, if a developer is not aware of that strong reference from the event source to the event subscriber.

**Comment by sialcasa** [comment]
Option A: 

Instead of using the global Notification Center we could create a local notification mechanism between the V and the VM. Maybe using a private NotificationCenter for the VM / V?

**Comment by sialcasa** [comment]
Option B-1: 

Break Interface of NotificationCenter to type of the channel params **Object channel**  (e.g. [in the subscribe method](https://github.com/sialcasa/mvvmFX/blob/a8ffbb10d9691cf1d421331da4b91ea56c1171bc/mvvmfx/src/main/java/de/saxsys/mvvmfx/utils/notifications/DefaultNotificationCenter.java#L97)) to String. This forces the users of the API not to provide objects that can get leaked but Strings that can't leak.

Therefor we could use **System.identityHashCode(yourObject)** instead of **this** in [the subscribe call in the ViewModel](https://github.com/sialcasa/mvvmFX/blob/develop/mvvmfx/src/main/java/de/saxsys/mvvmfx/ViewModel.java#L64) (and other methods in the Interface), to correlate between the VM and the V

Option B-2:

Use **System.identityHashCode(yourObject)** instead **this** [here in the ViewModel](https://github.com/sialcasa/mvvmFX/blob/develop/mvvmfx/src/main/java/de/saxsys/mvvmfx/ViewModel.java#L64)  (and other methods in the Interface), to correlate between the VM and the V. 
The difference is not to beak the NotificationCenter API.

Option 3:

Use WeakReferences instead of holding the VM / Scope References in the ChannelObserverMap

**Comment by sialcasa** [comment]
I think in the first step my prefered choice would be to have a specific NotificationCenter between VM and V (same goes for Scope) that is referenced by the VM. Then we would avoid the need of unsubscribing or using WeakListeners (https://github.com/sialcasa/mvvmFX/issues/286), because the NotificationCenter is only referenced by the VM.

In the second step we have to fix https://github.com/sialcasa/mvvmFX/issues/286 that may break the NotificationCenter.

**Comment by manuel-mauky** [comment]
Comment to Option 3 (using a WeakReference instead of the VM/Scope as channel object):
This won't work out of the box. 
For each method (`subscribe`, `publish` and `unsubscribe`) instead of using `this` as channel object we would need to create a `new WeakReference<>(this)` as channel object. 
However,  `WeakReference` doesn't override `equals` and `hashcode`. Therefore each time one of these methods is called, a new channel is created. 
To fix this we would need to subclass `WeakReference` and override `equals` and `hashCode` by ourselfs. To do this we could use the wrapped reference object. However this sounds a little bit crazy for me and I don't know if this would create other issues.

I've tested this approach locally and at least all existing unit tests for notifications are still green. Don't know if it fixes the memory problems.

**Comment by manuel-mauky** [comment]
Comment to Option B-2 (using `System.identityHashCode(this)` as channel object):
I have tested this too and all existing unit tests are still green.

**Comment by gtnarg** [comment]
Comment to Option 3 - (using a WeakReference instead of the VM/Scope as channel object):
Couldn't  channelObserverMap be a WeakHashMap?

**Comment by manuel-mauky** [comment]
Using a WeakHashMap would indeed solve the problem with the channels.
However I'm asking myself if this would be an API breaking change: A developer can use the existing API of the notification center and with another channel object (whatever that object might be). If we change the internal map to WeakHashMap, maybe existing code will break because now the observers are lost if the channel object is garbage collected. 
On the other hand, if you like to send a message you need a reference to the channel object so it can't be garbage collected at this point in time. Or do I miss something?

**Comment by manuel-mauky** [comment]
This issue is fixed but will only be part of Release 1.5.0 and not 1.4.2
The reason is that the fix needed an API change in the NotificationCenter where the type of the channel object is now `Object` instead of `ViewModel`. 
This change was done as part of #154 and PullRequest #322
