### ISSUE TITLE
Lifecycle Concept for View / ViewModels.

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#381]
There is already a lifecycle hook (Initialize). It would be great to have the possibility to have other phases like a dispose() hook, that is called when the user decided to kill a group of views. 

Dispose should 
- give the user the option to remove Observers from the NotificationCenter or other long living objects
- allow the user to do house-keeping before the View and ViewModel are killed

**Comment by sialcasa** [comment]
Maybe a compromise would be to have hooks that tells the user whether a view was moved or removed into / from the scene graph.

The ViewModel Interface could get a:

onViewShown //Different naming --> too View specific

onViewRemoved

During the loading of the view in the FluentViewLoader we could register a listener on the sceneProperty of the loaded view to call onViewShown / onViewRemoved, when the view was removed / added to a scene. Then the user could use those methods to implement the housekeeping. 

In addition we should discuss whether this should be a part of the ViewModel Interface or another Interface, that can be used in addition to the ViewModel Interface.

**Comment by sialcasa** [comment]
Think about Scenes that are not displayed in a window

**Comment by manuel-mauky** [comment]
Added a prove of concept for livecycles (185191ab6c).
However, I think that the POC implementation itself produces memory leaks due to listeners with references to the viewModel. Of cause this has to be fixed because otherwise this whole feature wouldn't make sence. 

Open points:
- [x] find better names
- [x] documentation
- [x] testing
- [ ] implementation for `JavaView`s

**Comment by manuel-mauky** [comment]
After some testing I have the feeling that not memory leaks are a problem but the exact opposite: In some situations the `onViewRemoved` isn't invoked because the viewModel was already garbage collected. 
If the user implements the livecycle interface we have to make sure that the ViewModel isn't garbage collected before the lifecycle methods are invoked. 
I'm working on this.

**Comment by manuel-mauky** [comment]
I've improved the implementation so that now the ViewModel won't be garbage collected until the "onRemoved" method is invoked. After that the framework will not guarantee any behavior regarding garbage collection. This behavior is useful for most typicall usecases were the livecycle is used to clean up other resources before the view/viewModel is thrown away. 
However, in some usecases were the view/viewModel are reused and put into the scenegraph a second time this behavior can be problematic: If garbage collection is running in between the viewModel will be collected and not livecycle methods are invoked. 

To prevent this we need #430. I will add special test cases to reproduce this use case when this feature is implemented. Additionally I will document both features together so that typical use cases are handled in the docs.

**Comment by manuel-mauky** [comment]
The current implementation still has a problem when GC is executed between livecycle invokation of multiple viewModels. Even if this is unlikely I will fix the implementation. At this point the implementation is still a prove of concept and more testing will be needed before we can be sure that everything works and nothing breaks.

**Comment by manuel-mauky** [comment]
My assumption about a problem with GC between livecycle invokations was wrong. At least a test case I've created shows that it works as expected. 
I will merge this into the current development branch so that it can be tested. As soon as #430 is implemented I will create additional test cases for both features in combination. 
For this purpose and for the open tasks (see [comment](https://github.com/sialcasa/mvvmFX/issues/381#issuecomment-239210851)) I will keep this issue open.

**Comment by manuel-mauky** [comment]
We will move the implemention of this feature for ViewModels of JavaViews and CodeBehind classes to the next version 1.7.0. 
See #470 and #471.
