### ISSUE TITLE
Change DelegateCommands parameter "executableBinding" from ObservableBooleanValue to ObservableValue<Boolean>

### ISSUE THREAD

**Issue by simonsilvalauinger** [sialcasa/mvvmFX#384]
It's more abstract and give you the freedom to do inline bindings.
This code

``` java
public class MyViewModel implements ViewModel {
   private final ObjectProperty<Object> op = new SimpleObjectProperty<Object>();
   private final BooleanProperty bp = new SimpleBooleanProperty(false);
   private final Command c = new DelegateCommand(() -> new Action() {
      @Override
      protected void action() throws Exception {
         // do whatever you want
      }
   }, bp);

   public MyViewModel() {
      bp.bind(EasyBind.monadic(op).map(Objects::nonNull));
   }
}
```

would be reduced to

``` java
public class MyViewModel implements ViewModel {
   private final ObjectProperty<Object> op = new SimpleObjectProperty<Object>();
   private final Command c = new DelegateCommand(() -> new Action() {
      @Override
      protected void action() throws Exception {
         // do whatever you want
      }
   }, EasyBind.monadic(op).map(Objects::nonNull));
}
```

**Comment by sialcasa** [comment]
I'm not sure but this binding may gets garbage collected with the current implementation. Can you please create a PR for it with tests that proves, that this works?

**Comment by manuel-mauky** [comment]
Hi @simonsilvalauinger 
thanks for your feature request. I think that @sialcasa  is correct and your code example wouldn't work in practice because the Binding `EasyBind.monadic(op).map(Objects::nonNull)` will be garbage collected because no reference exists.

But besides this of cause your initial request is valid and the parameter could also be of type `ObservableValue<Boolean>`. The reason for using `ObservableBooleanValue` in the first place was that the internal implementation is easier because it provides a binding for logical AND.

In #389 I have created an low-level-binding instead and changed the parameter type.

Existing code will not break because `ObservableBooleanValue` extends `ObservableValue<Boolean>`.
