### ISSUE TITLE
ValidationStatus#getMessages return value has changed

### ISSUE THREAD

**Issue by gtnarg** [sialcasa/mvvmFX#415]
I have subclassed ValidationMessage  and am using them in a CompositeValidator,  This previously worked.  As of 1.5.2, the following code fails:

`List<MyValidationType> validationMessages = compositeValidator.getValidationStatus().getMessages();`

with the following error:

`de.saxsys.mvvmfx.utils.validation.CompositeValidationStatus$CompositeValidationMessageWrapper cannot be cast to mypackage.MyValidationMessage`

Is there any way to get access to the actual validation messages?

**Comment by manuel-mauky** [comment]
Sorry for the problem. I haven't had such use case in mind when I was refactoring the Composite Validator. I assume the problem came up with 1.5.1 and this issue #398 and this fix #401.

**Comment by manuel-mauky** [comment]
Hi,
I've refactored the `CompositeValidationStatus` class. It now uses another approach instead of a wrapper class. I've added a [test case](https://github.com/sialcasa/mvvmFX/commit/4e863978cdca13f60bdb8ed435006806a611ace8#diff-2b57abc1a43cc682dfffce34e47858cfR91) that shows the usage of a Custom validationMessage type too.

I hope this solves your problem.

However the actual code you provided doesn't compile and I think it wasn't compiling in previous versions neither because the return type of `ValidationStatus.getMessages()` is (and always was) `ObservableList<ValidationMessage>`. This can't be casted to `List<MyValidationType>` due to java's poor type system. 
However it's possible to cast actual instances inside the list (this is now possible again). Your code could look like this:

``` java
List<MyValidationType> validationMessages = 
    compositeValidator.getValidationStatus().getMessage()
    .stream()
    .map(m -> (MyValidationType) m) // this wasn't possible
    .collect(Collectors.toList());
```

@sideisra Can you review the code and test it in your project? All tests are green but maybe there are still corner cases for which we don't have test cases yet.

**Comment by gtnarg** [comment]
I have tested it, and it is working correctly on my side.  Thanks for the quick response :)

Sorry, I had sanitized my code for the purposes of explaining the problem - the actual code is:

```
    public ObservableList<MyValidationMessage> getValidationMessages(){
        return EasyBind.map( getValidationStatus().getMessages(),
                validationMessage -> (MyValidationMessage)validationMessage);
    }
```

which is consistent with your example.

**Comment by sideisra** [comment]
@lestard looks good :+1:

**Comment by manuel-mauky** [comment]
Ok cool. So I will merge this with develop so it can be tested with version `1.6.0-SNAPSHOT`.
