### ISSUE TITLE
[ModelWrapper] Set property-name for identified fields

### ISSUE THREAD

**Issue by pkantner** [sialcasa/mvvmFX#423]
The method `field(identifier, getter, setter)` takes an identifier as first argument. As an improvement, it would be good, if the returned property would have this identifier set as its name.

Example of StringProperty
Usage:

``` Java
StringProperty familyName = wrapper.field("familyName", Person::getFamilyName, Person::setFamilyName);
Assert.assertEquals("familyName", familyName.getName());
```

Possible implementation:

``` Java
public StringProperty field(String identifier, StringGetter<M> getter, StringSetter<M> setter) {
    return addIdentified(identifier, new BeanPropertyField<>(getter, setter, () -> new SimpleStringProperty(null, identifier)));
}
```

**Comment by manuel-mauky** [comment]
Hi Philipp,
this is a good idea. Don't know why we haven't done this already ;-)

**Comment by manuel-mauky** [comment]
While implementing this I was just thinking if it would be a good idea to also set the the ["bean" property](https://docs.oracle.com/javase/8/javafx/api/javafx/beans/property/ReadOnlyProperty.html#getBean--) (the first parameter of `new SimpleStringProperty(bean, name)`)? One could argue that the created properties are belonging to the modelWrapper instance. But on the other hand the modelWrapper is not a "real" bean. It doesn't have fields for the provided properties and also no `getX`, `setX`, `xProperty` methods. For this reason I will leave the "bean" null.

**Comment by pkantner** [comment]
Or, maybe one would rather expect that "bean" is the model instance, that is wrapped in the ModelWrapper.

**Comment by manuel-mauky** [comment]
I thought about this too but after thinking a little longer about this I think we shouldn't set the "bean" property: 
The model instance doesn't "really" contain these properties neither. 
As far as I know the "bean" value is intendet to be used by certain tools to implement magic that otherwise would be implemented with reflection. Maybe we provide wrong assumtions for such tools if we set the beans field incorrectly. 
The second and more important argument against this is that the wrapped model instance can be changed at runtime. However the "name" and "bean" attributes can only be set in the constructor of the Property. After the user changed the model instance, the "bean" property would be a wrong information. Additinally the property would keep a reference to the first model instance which prevents garbage collection of this model instance resulting in a memory leak.

**Comment by pkantner** [comment]
You are right. So leaving the "bean" unset should be the best way to go.
