### ISSUE TITLE
Controller/CodeBehind gets garbage collected when View is loaded with FluentViewLoader

### ISSUE THREAD

**Issue by maimArt** [sialcasa/mvvmFX#429]
Hi,

in our project we dynamically change the center content of our view.

So i am doing stuff like:
`ViewTuple centerViewTuple= fluentViewLoader.fxmlView(viewType).load(); 
`
`centerPane.getChildren().clear();`
`centerPane.getChildren().add(centerViewTuple.getView());`

If i load the view like that without explicitly holding a reference to its code behind the controller/codeBehind will be garbage collected immediatly.
Of course if i add a strong reference of the controller to the viewmodel by adding a listener to a property of the viewmodel for example, the controller will also not be garbage collected.
But if i only use weak bindings like in most mvvm use cases the controller will be garbage collected if i don´t explicitly hold a reference to it like that:

`private ViewTuple centerViewTuple;`

`private void xyz(Class<? extends FxmlView> viewType){`
`centerViewTuple= fluentViewLoader.fxmlView(viewType).load(); 
`
`centerPane.getChildren().clear();`
`centerPane.getChildren().add(centerViewTuple.getView());`
`}`
I am not sure if it is a general problem of the javafx framework but i spent some time to find the failure So possibly other guys will fall over the same pitfall and you could mention this behaviour in your documentation.

Greets from Munich

**Comment by manuel-mauky** [comment]
Hi,
this is a general problem of JavaFX. Here is another example of this problem:[code](https://gist.github.com/lestard/9437412aeaee2a6480a993c6eb1266eb). 
JavaFX doesn't always hold a strong reference to the controller class of a FXML file. 

There are (at least) two situations were the controller isn't garbage collected: 
1. when you add a listener to a UI controll and that listener can not be inlined to a static method at runtime. This is the case when you access class members of the controller inside of the listener. 
2. when your fxml file references methods from the controller, for example `<Button onAction="#myMethod">`.  In this case the controller instance is needed to execute the method when the button is pressed. 

This behaviour is indeed a tricky but it's the default behaviour of JavaFX.
However, at the moment I'm thinking about providing a mechanism to prevent this behaviour for mvvmFX. For example there could add an interface `PreventGC` (or find a better name) that the CodeBehind could implement. Our loading mechanism can then keep a reference to this class so that it isn't garbage collected. However, the developer needs a way to "release" the reference programmatically to prevent memory leaks. In the `PreventGC` interface there could be a `default void release()` method for this case.

**Comment by maimArt** [comment]
Thanks for you quick reply and your suggestions. 
Nice that you are going to handle this problem in your improved fxmlLoader. I saw that you are already offering IClearable and a PropertyListenerManager to improve your lifecyle in 1.6.0 
So i will handle the problem with the workaround and check your future releases.

**Comment by emcastro** [comment]
Personnally, I pour the controller in the userData of the root object of the FXML

```
    FXMLLoader loader = new FXMLLoader(MyClass.class.getResource("myUI.fxml"));

    Pane ui = loader.load(); // let's suppose it's a Pane, your type may vary
    MyController uiController = loader.getController();

    // Prevents the GC to throw the controller away too early
    ui.setUserData(uiController);
```

**Comment by manuel-mauky** [comment]
Hi emcastro,
thanks for your hint. Your solution prevents the GC as well. 
However, it's not so easy when you have embedded FXML files. 

In this case you need to set an `fx:id` on the root element in the FXML file, 
inject a reference to the root node in your controller class and write `root.setUserData(this)` in the initialize method (therefore `this` points to the actual instance of the controller). 
This should work but it's not obvious for other developers why this is done in the code. It's not really descriptive. 
A marker interface with a descriptive name could be beneficial in such situations.
