### ISSUE TITLE
@InjectContext in ViewModel

### ISSUE THREAD

**Issue by maimArt** [sialcasa/mvvmFX#432]
Hi,

why is it only possible to inject the context in the View not the ViewModel?
Contexts hold Scopes that are provided by the ViewModel and injected in the ViewModel.

At the moment the injection of scopes by FluentViewLoader.context(Context) and FluentViewLoader.provideScopes(Scope...) are contradictory because their parameters are living in different layers.

I know the context is only needed when loading new Views not included in the current Context but i think the architecture would be nicer if they anyway are provided by the ViewModel not the View.

Greetings

**Comment by manuel-mauky** [comment]
Hi,
the context is kind of a "necessary evil". We wish we wouldn't need it but when the user loads another view with FluentViewLoader we have two FXML graphs without a link to each other. For this reason the user has to provide this "missing link" in form of the context. Maybe in the future we are able to completely remove the context handling for users. 
With this in mind we thought it would be the best to keep the handling of the context as small as possible without involving the viewmodel at all. One could argue that it's a view specific weakness that makes the context necessary in the first place. Why should the viewModel be concerned about this? 

But on the other hand I can understand arguments agains this too: The viewModel could have a method to get the context so that the view doesn't need to bother were the context comes from. 

Technically it would be easy to inject the context into the ViewModel too but I'm not convinced yet that this really is a cleaner approach. But maybe I'm overlooking something and I would be happy to be proven wrong ;-)

**Comment by maimArt** [comment]
Please dont missunderstand. I love your framework, i just want to know and maybe can help to improve it by my feedback :-)

My main use case is that i have a main view that dynamically loads its different contents. So the shown content is part of the ViewModel of my main view.

This is the reason why my question came up:

In my ViewModel i prepare all the ViewModel stuff for the content view i want to attach in the mainview. Dynamically inject scopes by the proveScopes()-method, perhaps even inject a prepared viewModel and stuff like that. I am really happy about how nice your framework handles this. But then i need the view layer to inject the global provided scopes by the context before i can load the view and provide its node to the view layer. I just was a little bit surprised why the view layer knows about the context not the viewmodel. 
Of course it´s no blocker and no problem to handle it like now. Just as you mentioned above. Perhaps there is a cleaner way to handle the scopes. And scopes are a quite new feature of your framework. So i am looking forward that it´s handling will improve by time.

Have a nice evening and thanks for the helpful and quick support

**Comment by manuel-mauky** [comment]
I'm really happy to get your feedback. And of cause I'm happy to hear that you like our framework. 

I think I get an idea of what you are trying to do but I've still some questions: Where do you invoke the `FluentViewLoader`? In the ViewModel or in the View? 
When I get you correctly you would like to get the context injected in your ViewModel? This sounds like you are trying to load the subview in your ViewModel. From a strict MVVM point of view this would be wrong. 
Maybe you can post some code snippeds so that I get a feeling of what you like to do?

**Comment by maimArt** [comment]
Yes i would prefere to inject the context in the viewmodel. But i just prepare the loader in an helper object of the viewmodel. The view finally calls the loader to load the view. I will post some snippets tomorrow.

**Comment by manuel-mauky** [comment]
Is this issue still relevant? At the moment I'm not convinced that injecting the Context in the ViewModel is a good idea. For this reason I will close this issue for now. If you still have a use case where this is needed, please reopen the issue and provide more details of what you like to achieve.
