### ISSUE TITLE
ViewModel and Scope get finalized

### ISSUE THREAD

**Issue by mainrs** [sialcasa/mvvmFX#450]
I just recently came across quite a big problem. To give you an idea on how my view looks I will shortly summarize it:

I have a `BorderPane` with a `MenuBar` at the top, a `StatusBar` at the bottom and a `NotificationPane` in the center. The `NotificationPane` has its content set to a `BorderPane`, lets call it B2. B2 contains a `SplitPane`, with the left content set to a `ListView` and the right one set to a `TilePane`.

The `NotificationPane` has its own View and ViewModel, as do each part of the `SplitPane`, creating a Master-Detail-View. If I trigger the `NotificationPane` it looks like all sub-views get garbage collected (at least the injected scopes and view models). I have no idea what is going on. 

I can upload the project (it is quite messy and I am not even finished with it), but the problem is there. Just take a look into the `MainView` class. I trigger the `NotificationPane` there after 5 seconds. Changing the focused item in the `ListView` will output the name of the item. But after another 1-2 seocond(s), the output will be:

`Finalized master view, master view model, detail view, detail view model`

This seems quite strange to me.

[Here](https://github.com/SirWindfield/motion) is the project I was working on, it is (for now) just a window with the above structure. It would be nice if someone could check this out, it seems quite odd to me...

**Comment by manuel-mauky** [comment]
Hi,
there is a problem with premature garbage collection of controllers in JavaFX in general. 
At the moment we have no utility to prevent this, however in issue #430 I've described this behaviour and gathered some ideas of how to implement this. But as up until now we had no replies or issues pointing in this direction we haven't given this a high priority. After all we thought that this might not be a very common use case. But now we know that there are actuall problems with this in real world apps.

The reason for this problem is that JavaFX itself doesn't keep a reference to the Controller class of a FXML file and if you as a developer don't create a hard reference from any element in the scenegraph to the controller class either then the controller class can be garbage collected.

As a dirty quick fix in the mean time you have to make sure that at least one ui element in the scenegraph is holding a hard reference to the viewModel.

**Comment by SirWindfield** [comment]
> As a dirty quick fix in the mean time you have to make sure that at least one ui element in the scenegraph is holding a hard reference to the viewModel.

How would I achieve this? Do you mean I need to make sure that the controller has a hard reference to the ViewModel? I thought I already did this by adding a ChangeListener to a ViewModel's property field.

**Comment by manuel-mauky** [comment]
Sorry, this was a little misleading. 
There is already a hard reference from the Controller to the Viewmodel but there is no hard reference to the Controller from the scenegraph. 

When you have a button in the fxml that defines a 'onAction="#someMethod"' clickhandler then there is a hard reference created. Another way is to add a listener to a property of any control. If you implement the listener as anonymous inner class you are save. If the listener is a lambda then it has to access any field of the controller. Otherwise it would be compiled to a static method invokation which doesn't produce a hard reference.

I know that this isn't a good solution. I have think about this a little longer to maybe find a better workaround.

**Comment by manuel-mauky** [comment]
Another cleaner way to prevent garbage collection is:

In your fxml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
...
<AnchorPane fx:controller="example.MyView" fx:id="root">
...
</AnchorPane>
```

Notice the `fx:id="root"`. In your CodeBehind:

``` java
class MyView implements FxmlView<MyViewmodel> {
    @FXML
    public AnchorPane root;

    public void initialize() {
         root.setUserData(this);
    }
}
```

This approach was suggested in https://github.com/sialcasa/mvvmFX/issues/429#issuecomment-247991630 and it works. This way the root AnchorPane keeps a reference to the Controller class / CodeBehind which prevents garbage collection

**Comment by manuel-mauky** [comment]
I'm closing this issue now because we have #430 to work on this and to discuss possible solutions.

For the mean time the workaround presented in this thread is still valid.
