### ISSUE TITLE
FXML Loader

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#5]
When the application is packaged as jar the Loader has issues

**Comment by manuel-mauky** [comment]
The problem is that non-java files in `src/main/java` are ignored when the application is packaged as jar. 
The fxml files are not included in the jar and therefore they can't be found by the FXMLLoader. 

Possible solutions:
- place fxml files in `src/main/resources/<package-structure>/` so that they are automatically included in the jar file
- configure/hack the maven-assembly/resource/? plugin so that fxml files are included in the jar even if they are located in `src/main/java`
