### ISSUE TITLE
mvvmFX with database interaction

### ISSUE THREAD

**Issue by No3x** [sialcasa/mvvmFX#510]
It's not really an issue but rather a question about best practice. You can't find much advice about this because it is the part where GUI becomes complex. You guys at saxsys build real world applications with this framework I guess. 

I try to figure out what's best practice regarding JPA/ORM/database lifecycles. Whenever the database changes you have to update the ViewModel. In the contacts example you use CDI events - whenever the database changes you fire an `contactsUpdatedEvent` to reload the GUI. Do you stick to this event based approach in real world applications or is there something better? Decision about this also influences the View/ViewModel logic. Maybe you can elaborate on this regarding clean design and your personal experience.

P.S. mvvmFX is more than just a framework. It helps me to separate concerns and influences my architecture for the better.

**Comment by manuel-mauky** [comment]
Thanks for the question. I think there is no general answer to this but I try to give you some thoughts about this topic.
In a real world application I was involved in at saxsys we have used an event-based approach similar to the one in the contacts example and it worked quite well but also had some downsides/challenges: 

1. You need to find out when the data in the database was updated. In our case there was only one application instance operating on a dataset at the same time so the only way that data could have been updated was by the application/user itself. This is easy. But in other scenarios you might need to now when another application instance has change some data and you have to find a way to be notified about this change. Someone (the database? JPA?) has to fire the update event. I don't know a general approach for such use cases.

2. How fine grained do you model your update events? In the contacts example there is one general "something has changed"-like event and all data is re-fetched from the database. In our application at saxsys we had a similar situation: The user was able to open a new tab to see data of a "customer" (I simplify and modify the use case a little bit). We had events to re-load the whole tab when the user changed some data for this "customer" entity. This way the context of data to refetch was limited and there was no performance issue even though many data fetches where unnecessary because only a small part of the data has changed. 
This approach is easy to implement but it's not possible for every use case. For some use cases you would need to fetch to much data. Instead you have to limit the data to re-fetch by a more fine grained modelling of the update events. Not "update everything" but instead "update customer with ID x" or "update the contract with ID X of customer with ID y".  However, some of these problems maybe can also be solved on the JPA layer by using a good caching strategy. This way you can stick with the simple "re-fetch everything" approach and let the JPA provider do the hard task of finding out what really needs to be reloaded from the database.

3. Where in your application are you listening to update events? In my point of view this is the biggest risk of this approach. Event-based approaches in general are good to decouple parts of an application but they are also make it harder to understand what actually happens in your app. You can push an "CustomerUpdatedEvent" and different parts of your application can respond to this event and load the data they need from the database. But if something when wrong it can be hard to find the reason. Where was the data loaded? How did the wrong data got into this component? It can become even worse if you fire new events based on other events. Then you get an event cascade. 
In our application we had some headaches with problems like this. This was one of the reasons we created the [scopes](https://github.com/sialcasa/mvvmFX/wiki/Scopes) feature. This way we can store data in a single place for one domain and have a cleaner way of passing this data to ViewModels. 
As I've said: Event-bases solutions have the positive effect of decoupling code and so it's a good solution but you have to keep the risks in your mind and keep the data flow clean. 

My advice is to use the scopes feature to have a single source of truth for a domain. The scope can load data from the database when needed. ViewModels take the data only from the scope (or many scopes if the viewModel is involved in different domains) instance and doesn't talk to the Database/JPA itself. 
In the application I've mentioned we would use a new scope for each tab to keep all the data for this customer.

I hope these thoughts can help you. I hope I haven't missed the actual topic because you've asked for the update event when something in the database changed and I've only mentioned this briefly. I haven't implemented an application with this specific use case yet but maybe we can still find a solution for your use case.

**Comment by No3x** [comment]
@lestard
thanks for your explanation. To be more specific:
> Whenever the database changes you have to update the ViewModel.

With this I meant `update`, `insert`, `deletes` trough the JPA Persistence Manager. No external changes or other applications sharing the same database. 

>2. How fine grained do you model your update events?

I would go with the coarse-grained event approach until hitting performance issues.

>3. Where in your application are you listening to update events? 

Scopes are really neat for this! I have tried them out to share the "Customer selected in X and shown in Y to edit" between the views X and Y. Consuming change events there would be the perfect place.

Do you think it is possible to avoid an event approach completely (given JPA and that the database is not shared by other applications)? So this means shifting the events to Observables (`ObservableObject`, `ObservableList` etc.)? At the moment [my models look like this](https://github.com/No3x/javafx-boilerplate-hibernate-lifecycles-1nn1/blob/651670489ed7305fbe85f416ce09d93fc99b52b4/src/main/java/sample/model/Person.java): There is a `ObservableList`/`ListProperty` for the gui to bind ListViews etc. and another list for JPA. Both need to be managed and be consistent. This is really annoying. Do you use the same approach?

At the moment I develop very simple projects to try out different architectures until I find a solid base to port this to a real application.

**Comment by manuel-mauky** [comment]
I don't think that avoiding events is even desirable in every use case. If your application has different parts that show the same data and in one part this data is updated then you have to notify the second part about this fact. you have (at least) two possible solutions: Part 1 can update Part 2 directly which is relatively easy to understand but introduces a dependency from Part 1 to Part 2. Or Part 1 can send out an event without knowing who is interested in this event. 
Deciding which solution to use for a specific use case is not easy and there is no general rule for this. It's the hard task of a software architect :-)

Observables are cool but also limited in JavaFX. The biggest problem is that it's hard to use this for nested data. Think of a "Customer" entity that has an observable list of "Contracts" and each "Contract" has an observable list of "Invoices". If you create a binding to a property in one of the "invoice" instances, what happens when the contracts observable list in customer instance changes? So observables are a really useful tool but have their downsides and as a developer you have to know when to use them and when not to.

Using observables has some similarities to the programming paradigm called "reactive programming" and there are programming languages directly optimized to this way of programming, even though they are not really popular anymore. I've written an article about this topic some time ago (however, it's in german): https://jaxenter.de/einfach-und-effizient-reactive-programming-mit-javafx-28498

I don't use Properties in JPA entities. My JPA entities are just plain Java Objects for the reasons mentioned above. Basically this is the whole reason we've developed mvvmFX because it's not that easy to directly use JPA (or another database lib) with JavaFX. It's the main task of the ViewModel to "translate" between the database and the observables used by the UI.

Just for completeness: There is also another way of implementing such apps that's called "redux". Redux is a pattern and a library for JavaScript that uses a functional programming approach for state management. I don't want to describe this in full length here but I personally find this approach really interesting and cool (however, of cause it has it's downsides too). And you can use Redux with JavaFX too, for example with [https://github.com/netopyr/reduxfx](reduxfx) which I'm also involed in. 
In my current project at saxonia systems we are using a similar approach (but with a non-public library) in combination with mvvmFX and it looks really promising.

I'm afraid I can't give you absolute directions but only some thoughts that hopefully can help you. And sorry for the late reply.

**Comment by No3x** [comment]
I'm currently trying out the 
> Part 1 can send out an event without knowing who is interested in this event.

approach and removed all observables from my model classes. As long there is no property aware collection implementation in JPA I can't think of using observables on model basis anymore - especially to update nested collections. All observables moved to the `ViewModel` and loaded once from the `Model` on initialisation. If something on the database changes all dependent components shall be updated and do a reload from the database.
I already know similar libs to reduxfx in android but not in detail.

I'm definitely still trying to find the best solution for my project. But my resources are limited to this hobby project as I don't get paid for it.
@lestard thank you very much for your perspective on this!

> I've written an article about this topic some time ago (however, it's in german): https://jaxenter.de/einfach-und-effizient-reactive-programming-mit-javafx-28498

Best regards from Bremen, Germany!

**Comment by manuel-mauky** [comment]
I've closed this issue because of little interaction lately but I can reopen it if you like.

If you get new insights on what works and what does not, maybe you can post these insights here. Having best practices documented for different kinds of projects would be nice.

**Comment by No3x** [comment]
No I'm fine with the closed state.
When I get a solid example I will share it here. Unfortunately the real problems will appear in the last 20% of implementation.
