### ISSUE TITLE
ModelWrapper with methods field / immutableField that accept arguments of type Set and Map

### ISSUE THREAD

**Issue by johandeschutter** [sialcasa/mvvmFX#531]
Hello,

Is possible to add to the ModelWrapper class the methods field / immutableField that accept arguments of type Set and Map .

Currently only the methods field / immutableField only accept collections of type List.

Something like this:
    public <E> SetProperty<E> field(SetGetter<M, E> getter, SetSetter<M, E> setter) {
        return add(new BeanSetPropertyField<>(this::propertyWasChanged, getter,
                (m, set) -> setter.accept(m, FXCollections.observableSet(set)), SimpleSetProperty::new));
    }

    public <E> MapProperty<E> field(MapGetter<M, E> getter, MapSetter<M, E> setter) {
        return add(new BeanMapPropertyField<>(this::propertyWasChanged, getter,
                (m, map) -> setter.accept(m, FXCollections.observableMap(map)), SimpleMapProperty::new));
    }

Regards,

Johan

**Comment by manuel-mauky** [comment]
Hi johandeschutter,
thanks for your request. At the moment this is not possible but it could be added. I don't see a reason why this would not work. It's missing because we hadn't had the need for this yet and based on my experience not many people are using SetProperty and MapProperty. 

I don't know when I find the time to add this feature. However, I'm happy to accept a PullRequest for this. Thinks to do are:
- [ ] Add getter/setter interfaces (`MapGetter`, `MapSetter`...)
- [ ] Extend the example classes for the tests (`Person.java`, `PersonFX.java` and `PersonImmutable.java`)
- [ ] Extend the unit tests in [ModelWrapperTest.java](https://github.com/sialcasa/mvvmFX/blob/develop/mvvmfx/src/test/java/de/saxsys/mvvmfx/utils/mapping/ModelWrapperTest.java)
- [ ] Implement the feature in ModelWrapper.
  - [ ] Add *Field classes like [BeanListPropertyField](https://github.com/sialcasa/mvvmFX/blob/develop/mvvmfx/src/main/java/de/saxsys/mvvmfx/utils/mapping/BeanListPropertyField.java) for Map and Set.
  - [ ] Implement overloaded `field` methods similar to the code you've already posted.

**Comment by manuel-mauky** [comment]
I've implemented the first part of this issue: You can now use Sets with the Model-Wrapper.
I will add support for Maps within the next days. It works the same way
