### ISSUE TITLE
Why does it crash after I use jpackage to package it into dmg, and what should I do? Here is my module-info.java

### ISSUE THREAD

**Issue by lqyaos** [sialcasa/mvvmFX#624]
Why does it crash after I use jpackage to package it into dmg, and what should I do? Here is my module-info.java

module com.example.packtest {
     requires javafx.fxml;
     requires de.saxsys.mvvmfx;
     requires javafx.controls;
     opens com.example.packtest to de.saxsys.mvvmfx,javafx.fxml;
     exports com.example.packtest;
}

**Comment by manuel-mauky** [comment]
I think that no one has tried using jpackage with mvvmFX yet.

I'm in the process of reworking the framework to use an up-to-date JDK and to use module system internally so that all dependencies are modeled correctly. I assume that this will help to use the framework with jpackage.
However, it still takes some time to finish this rework.

**Comment by lqyaos** [comment]
Thanks for your reply, so how do I pack it? Because I need the running environment of jdk11

**Comment by lqyaos** [comment]
hi I have packaged it out using the jpackage non-modular command thank you
